version: '3.8'

services:
  mock-api:
    build: .
    container_name: qa_mock_server
    ports:
      - "8000:8000"
    environment:
      - ENV=DOCKER_QA
      - BASE_URL=http://localhost:8000
      # 【核心魔法 1】：让服务器把数据库建在这个特殊的 shared_data 文件夹里
      - DB_NAME=/app/shared_data/test_business.db
    # 【核心魔法 2】：把下面声明的共享 U 盘，插到容器的 /app/shared_data 目录
    volumes:
      - qa-shared-data:/app/shared_data
    restart: always

  test-runner:
    build: .
    container_name: qa_test_runner
    command: sh -c "sleep 5 && pytest tests/ -s"
    depends_on:
      - mock-api
    environment:
      - ENV=DOCKER_QA
      - BASE_URL=http://mock-api:8000
      # 【核心魔法 3】：让测试脚本也去这个特殊的 shared_data 文件夹里读数据库
      - DB_NAME=/app/shared_data/test_business.db
    # 【核心魔法 4】：把同一块共享 U 盘，也插到测试机里，实现文件互通！
    volumes:
      - qa-shared-data:/app/shared_data

# 【核心魔法 5】：向 Docker 申请一块名字叫 qa-shared-data 的虚拟共享磁盘
volumes:
  qa-shared-data: